CREATE TABLE CUSTOMER (
  CUSTOMER_TYPE           VARCHAR(255) NOT NULL,
  CUSTOMER_ID             BIGINT       NOT NULL AUTO_INCREMENT,
  TEXT_VALUE              VARCHAR(255),
  STAFF_MEMBER_ID         BIGINT,
  STAFF_MEMBER_FIRST_NAME VARCHAR(255),
  STAFF_MEMBER_LAST_NAME  VARCHAR(255),
  TABLE_NUMBER            BIGINT,
  TABLE_DISPLAY_VALUE     VARCHAR(255),
  PRIMARY KEY (CUSTOMER_ID),
  FOREIGN KEY (STAFF_MEMBER_ID) REFERENCES STAFF_MEMBER (STAFF_MEMBER_ID)
);

CREATE TABLE ITEM_ORDER (
  ITEM_ORDER_ID           BIGINT         NOT NULL AUTO_INCREMENT,
  CUSTOMER_ID             BIGINT         NOT NULL,
  NOTE                    VARCHAR(255),
  ORDER_TIME              TIMESTAMP      NOT NULL,
  STATUS                  VARCHAR(255)   NOT NULL,
  ITEM_ID                 BIGINT         NOT NULL,
  ITEM_TITLE              VARCHAR(255)   NOT NULL,
  ITEM_PRICE              DECIMAL(19, 2) NOT NULL,
  ITEM_TYPE               VARCHAR(255)   NOT NULL,
  STAFF_MEMBER_ID         BIGINT         NOT NULL,
  STAFF_MEMBER_FIRST_NAME VARCHAR(255)   NOT NULL,
  STAFF_MEMBER_LAST_NAME  VARCHAR(255)   NOT NULL,
  PRIMARY KEY (ITEM_ORDER_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
  FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID),
  FOREIGN KEY (STAFF_MEMBER_ID) REFERENCES STAFF_MEMBER (STAFF_MEMBER_ID)
);

CREATE TABLE OPTION_ORDER (
  OPTION_ORDER_TYPE VARCHAR(255)   NOT NULL,
  OPTION_ORDER_ID   BIGINT         NOT NULL AUTO_INCREMENT,
  VALUE             INTEGER,
  CHECKED           BOOLEAN,
  OPTION_ID         BIGINT,
  OPTION_TITLE      VARCHAR(255)   NOT NULL,
  OPTION_PRICE_DIFF DECIMAL(19, 2) NOT NULL,
  RADIO_ITEM_ID     BIGINT,
  ITEM_ORDER_ID     BIGINT,
  PRIMARY KEY (OPTION_ORDER_ID),
  FOREIGN KEY (ITEM_ORDER_ID) REFERENCES ITEM_ORDER (ITEM_ORDER_ID),
  FOREIGN KEY (OPTION_ID) REFERENCES ITEM_OPTION (OPTION_ID),
  FOREIGN KEY (RADIO_ITEM_ID) REFERENCES RADIO_ITEM (RADIO_ITEM_ID)
);
