CREATE TABLE STAFF_MEMBER (
  STAFF_MEMBER_ID BIGINT       NOT NULL AUTO_INCREMENT,
  FIRST_NAME      VARCHAR(255) NOT NULL,
  LAST_NAME       VARCHAR(255) NOT NULL,
  PRIMARY KEY (STAFF_MEMBER_ID)
)
