= BonAppetit
Claudius Boettcher <pos.bonappetit@gmail.com>
2016-07-08
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../java]

This is the documentation of the open source Point-of-Sale system BonAppetit.

== Use Cases

TBA

== Non-Functional Requirements

TBA

== Domain Model

[plantuml, domain-model, png]
....
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Declaration
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Menu & Item
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
class MenuConfig
class Menu
class Item {
    title : String
    price : BigDecimal
}
enum ItemType {
    FOOD
    DRINK_ALCOHOLIC
    DRINK_NON_ALCOHOLIC
    SIDE_DISH
}

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Options
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
abstract class Option {
    title : String
    index : Integer
}
class ValueOption {
    priceDiff : BigDecimal
    defaultValue : Integer
}
class RadioOption
class CheckboxOption {
    priceDiff : BigDecimal
    defaultChecked : boolean
}

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Orders
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
class ItemOrder {
    deliverTo : String
    orderTime : DateTime
    note : String
    totalPrice : BigDecimal
    discount : Integer
}

abstract class  OptionOrder
class ValueOptionOrder {
    value : Integer
}
class RadioOptionOrder
class CheckboxOptionOrder
enum OrderState {
    ORDERED
    PRINTED
    PAID
    CANCELLED
}

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Staff
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
class StaffMember {
    firstName : String
    lastName : String
}

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Associations
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
MenuConfig --> "1" Menu : active
Menu --> "1..n" Item
Item --> "0..m" Item : sideDishes
Item --> ItemType : type
Item --> "0..n" Option : options

Option <|-- ValueOption
Option <|-- RadioOption
Option <|-- CheckboxOption
RadioOption --> "1" RadioItem : defaultSelected
RadioOption --> "2..n" RadioItem : radoioItems

ItemOrder --> "1" OrderState : state
ItemOrder --> "1" StaffMember : orderedBy
ItemOrder --> "1" Item : item
ItemOrder --> "0..n" OptionOrder : optionOrders

OptionOrder <|-- ValueOptionOrder
OptionOrder <|-- RadioOptionOrder
OptionOrder <|-- CheckboxOptionOrder

ValueOptionOrder --> "1" ValueOption : option
RadioOptionOrder --> "1" RadioItem : selectedItem
CheckboxOptionOrder --> "1" CheckboxOption : option
....

TBA

== Functional Architecture (A-Architecture)

TBA

== Technical Architecture (T-Architecture)

TBA

== Technical Infrastructure Architecture (TI-Architecture)

TBA

== Implementation Architecture (I-Architecture)

The following illustration shows the canonical package structure of a business
component for the example "Foo"-component.

[plantuml, i-architecture, png]
....
@startsalt
{
{T
 + foo
 ++ to
 ++ fc
 +++ impl
 +++ mock
 ++ ba
 ++ et
 ++ dao
 +++ impl
 +++ mock
}
}
@endsalt
....

foo::
    The top level package is named after the component. It contains the public API interface, parameter and exception
    types of the component.
    to;; The transport objects (DTOs) that the component hands to the caller.
    fc;; The facade package contains the implementations of the top level api interfaces.
        impl::: The production impls of the top level api interfaces.
        mock::: Contains mock implementations of the top level api interfaces that.
    ba;; The business activities package contains the implementations of the provided business functions.
    et;; The entities package contains the entity types which are mapped to the database.
    dao;; The data access objects package contains the data access layer api interfaces.
        impl::: The real impl of the daos.
        mock::: A mocked impl of the daos that provide test data.

== UI Concept

TBA