== Operations

In this section you will find all you need to know to operate BonAppetit.

=== Dependencies

The BonAppetit server requires

* Java SE Runtime Environment 8 or higher.
* A SQL database.
* A directory in the file system where log files are stored. Referred to as `BONAPPETIT_BASE`, see <<Configuration>>.
* An external properties file where you specify your database and other settings, see <<External Configuration>>.

=== Configuration

[[bonappetit-base]]

==== Base Directory (aka BONAPPETIT_BASE)

The BonAppetit Server requires a directory referred to as `BONAPPETIT_BASE`.
This is the location where the server writes its log files.

The BONAPPETIT_BASE directory has the following layout

[plantuml, BONAPPETIT_BASE_layout, png]
....
@startsalt
{
{T
 + BONAPPETIT_BASE
 ++ log
 +++ bonappetit-server.log
}
}
@endsalt
....

BONAPPETIT_BASE::
    The BONAPPETIT_BASE root directory.
    log;; All log files generated by the BonAppetit Server are written to this directory. The log file is rotated
    as soon as its size reaches 10MiB.

==== Authentication and Authorization

All server endpoints are secured via basic auth. Username and password are expected in form of an authorization
header in all requests to the server
(see https://en.wikipedia.org/wiki/Basic_access_authentication[Basic Auth @ *Wikipedia*]).

==== External Configuration

The main external configuration is read from `bonappetit.properties`. Its location must be handed to the jar on startup
(see <<JVM Parameters>>). The BonAppetit Server
project is a http://projects.spring.io/spring-boot/[Spring Boot] application. Therefore the
`bonappetit.properties` file
can be used to provide or override any
http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html[common Spring Boot application property]
that can be used in the standard `application.properties`.

The following properties consisting of standard spring boot as well as of bonappetit specific properties are
especially important:

.External configuration via bonappetit.properties
|====
|Name |Required |Description |Default |Example

|security.admin.username
|true
|The username of the admin user. This is the only user that is authorized to manage API users via the `/api/users` REST endpoints.
|-
|admin

|security.admin.passwordHash
|true
|The salted password hash of the admin user (see `security.admin.username`). Must be computed using the open source library https://github.com/qaware/heimdall[Heimdall]
|-
|1:1:unf6gJNOOlayrKyEQgfEk7 K4RvwhW9WI:i=4e20:gH613KUcJ OtL1UcPUadsVvAUoUfvPBoS

|spring.datasource.url
|false
|The URL of the database where all data (staff members, orders, etc.) is stored. Per default the server is configured to use a
https://www.mysql.de/[MySQL database] with a schema named `bonappetit` running at `localhost:3306`.
|jdbc:mysql://localhost/bonappetit
|jdbc:mysql://localhost/bonappetit, jdbc:mysql://localhost/my-restaurant

|spring.datasource.username
|false
|The database user that is used to access the database
|bonappetit
|bonappetit,peter

|spring.datasource.password
|true
|The password to use to authenticate `spring.datasource.username` against the database.
|-
|s3cr3t

|flyway.enabled
|false
|Whether flyway migration is performed on server startup. Warning: do not enable this option when working with a
production database. Instead: Do a dry run of the migration on a copy of your production database (Production databases
always contains surprises). Then apply the migration manually to the production database.
|false (profile PROD), true (profile LOCAL), see <<Profiles>>
|true, false

|printing.printService.name
|true
|The name to use when looking up the `javax.print.PrintService` to use. This is usually the display name of the
printer.
|-
|CITIZEN CT-S310II

|printing.timeZone.id
|true
|The timezone id to use for formatting dates when printing. Internally all dates are processed in UTC.
|-
|Europe/Berlin

|printing.options.emphasised
|false
|Comma separated list of the titles of the options or radio items which should be printed in an emphasised way.
At the moment to emphasize an option means to print it big and bold next to the item title. E.g. if you configure
an item with the title "Pizza" and a Radio-Option with title "sort" and two radio items with the titles "Hawaii" and "Capricciosa"
you can set this property to "Hawaii,Capricciosa" to make the printer print "Pizza Hawaii" as item title instead
of printing "Pizza" as item title and "Hawaii" as standard option below the title.
|-
|small,Hawaii,light

|printing.options.notPrinted
|false
|Comma separated list of the titles of the options or radio items which should not be printed at all. Some options
like size have to be selectable when taking an order but they do not have to be printed. E.g. the default for
the size of a drink might be "big" so we don't hve to print it.
|-
|big
|====

==== Profiles

Profiles control what configuration the BonAppetit Server is run in (Specified on startup
via <<JVM Parameters>>).

Table <<table_profiles>> lists the existing profiles.

[[table_profiles]]
.Profiles
|===
|Name| Description

|PROD
|Configures the BonAppetit Server for production use. Automatic database migration on startup is disabled.

|LOCAL
|Configures the BonAppetit Server for local use. Automatic database migration on startup is enabled.
|===

See <<JVM Parameters>> to learn how you select the profile.

==== JVM Parameters

Table <<table_jvm_params>> lists the JVM parameters that are supported by the BonAppetit-Server. Note that you have to
prefix them with -D when running from the command-line.

[[table_jvm_params]]
.JVM parameters
|===
|Name |Required |Description |Default |Example

|BONAPPETIT_BASE
|true
|The path of the base directory where logs are stored.
|-
|"M:\bonappetit-base", "BONAPPETIT_BASE", ".", "/home/peter/bonappetit-base"

|spring.profiles.active
|true
|The profiles to activate. Profiles control the server configuration, e.g. the database URL and credentials.
PROD means the server is run in production configuration. LOCAL is only relevant to developers working with a database
that contains only test data.
|-
|PROD, LOCAL

|spring.config.location
|true
|The location of the bonappetit.properties file. Due to spring boot internals this has to be defined via program
argument explicitly.
|-
|"M:\BONAPPETIT_BASE\config\bonappetit.properties"
|===