=== Implementation Architecture (I-Architecture)

==== BonAppetit Server

The following illustration shows the canonical package structure of a business
component for the example "Foo"-component.

[plantuml, i-architecture, png]
....
@startsalt
{
{T
 + foo
 ++ to
 ++ fc
 +++ impl
 +++ mock
 ++ ba
 ++ et
 ++ dao
 +++ impl
 +++ mock
}
}
@endsalt
....

foo::
    The top level package is named after the component. It contains the public API interface, parameter and exception
    types of the component.
    api;;
        The api package contains all parts of the public API of the business module (interfaces, exceptions, dtos)
        to::: The transport objects (DTOs) that the component hands to the caller.
    impl;; The impl package contains the implementations of the top level api interfaces.
        impl::: The production impls of the top level api interfaces.
        mock::: Contains mock implementations of the top level api interfaces that.
    entity;; The entities package contains the entity types which are mapped to the database.
    dao;; The data access objects package contains the data access layer api interfaces.
        impl::: The real impl of the daos.
        mock::: A mocked impl of the daos that provide test data.

The packages api and api.dto are part of a separate module to be reusable in client code (as jar).

==== BonAppetit Android App

===== Layout Style Guide

The following guidelines are partly based on the following articles:

* https://github.com/futurice/android-best-practices

**Layout XML vs. Style**

Keep only layout (positioning, margin, sizing) and content attributes in the layout files,
while keeping all appearance details (colors, padding, font) in styles files.

Attributes that are defined in the layout XML:

* `android:id`
* `android:layout_****`
* `android:orientation` for a `LinearLayout`
* `android:text`
* `android:layout_width` and `android:layout_height`

Other `android:****` should stay in a style XML

**Attribute Order and format**

* One attribute per line
* `android:id` as the first attribute always
* `android:id` is only present if required to reference the view
* `android:layout_****` attributes at the top
* `style` attribute at the bottom
* Tag closer `/>` on its own line, to facilitate ordering and adding attributes.

[source,xml]
----
<ListView
            android:id="@+id/staffMembersListView"<!--1-->
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            style="@style/MyListView.SpecialStyle"<!--2-->
            />
----
<1> `android:id` attribute in camelCase
<2> `style` attribute in PascalCase