=== Implementation Architecture (I-Architecture)

==== BonAppetit Server

The following illustration shows the canonical package structure of a business
component for the example "Foo"-component.

[plantuml, i-architecture, png]
....
@startsalt
{
{T
 + foo
 ++ to
 ++ fc
 +++ impl
 +++ mock
 ++ ba
 ++ et
 ++ dao
 +++ impl
 +++ mock
}
}
@endsalt
....

foo::
    The top level package is named after the component. It contains the public API interface, parameter and exception
    types of the component.
    to;; The transport objects (DTOs) that the component hands to the caller.
    fc;; The facade package contains the implementations of the top level api interfaces.
        impl::: The production impls of the top level api interfaces.
        mock::: Contains mock implementations of the top level api interfaces that.
    ba;; The business activities package contains the implementations of the provided business functions.
    et;; The entities package contains the entity types which are mapped to the database.
    dao;; The data access objects package contains the data access layer api interfaces.
        impl::: The real impl of the daos.
        mock::: A mocked impl of the daos that provide test data.

==== BonAppetit Android App

===== Layout Style Guide

[source,xml]
----
<ListView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/staffMembersListView"/><!--1-->
----
<1> android:id attributes in camelCase